### ISSUE TITLE
Update pipsi on pypi

### ISSUE THREAD

**Issue by bjoernpollex** [mitsuhiko/pipsi#49] opened 2015-06-17 21:16 UTC
The recommended way to install pipsi seems to be to use the `get_pipsi.py` script from the repository. This script effectively uses `pip install pipsi`, which installs an older version from pipy. This had me confused because I was getting errors that were inconsistent with the code on `master`. Specifically the version currently on pypi doesn't work at all with Python 3, and the support environment variables seems to be broken as well. Installing directly from `master` fixes all these issues. Would it be possible to push a new release to pipy?

**Comment by bomattin** [comment] 2015-06-22 15:22
Holy crap...this had been driving me nuts for a week. Thanks for posting this. For users coming here, the way to do this is as follows:

```bash
# Switch to your virtualenv, if desired
git clone https://github.com/mitsuhiko/pipsi.git
pip install -e pipsi
```

That's it.

**Comment by srstevenson** [comment] 2015-07-04 14:59
I'd appreciate a new release too, like @bjoernpollex I didn't know why `$PIPSI_BIN_DIR` and `$PIPSI_HOME` were being ignored until I checked `pipsi --version`.

**Comment by blueyed** [comment] 2015-07-12 08:44
Duplicate of #36.

**Closed** 2015-08-12 21:04 UTC
